services:
  frontend:
    restart: unless-stopped
    environment:
      VITE_API_URL: https://api.integrumsoft.com.br
    networks:
      - poda-arvores-network
      - rede-proxy

  backend:
    restart: unless-stopped
    environment:
      CORS_ORIGIN: https://integrumsoft.com.br
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: poda_user
      DB_PASSWORD: poda_pass
      DB_NAME: poda_arvores
    networks:
      - poda-arvores-network
      - rede-proxy

networks:
  poda-arvores-network:
    driver: bridge

  rede-proxy:
    external: true